### ISSUE TITLE
NX - Access to plugin directory - password required

### ISSUE THREAD

**Issue by ckuntze** [ptr727/NxWitness#124]
### Describe the problem?
Access to plugin directory - password required

Steps to reproduce:
New Testinstallation - no changes
Install Plugins in 
/opt/networkoptix/mediaserver/bin/plugins and /opt/networkoptix/mediaserver/bin/plugins_optinal need a passwort

Configuration:
Synology Docker
NX 5.1.2.37996

With NX-LSIO, the release for the other file systems does not work for me (fuse.shfs,btrfs,zfs)

**Comment by ptr727** [comment]
Please provide more information.  
What does password required mean?  
Is the comment about other filesystems related or a different issue?

**Comment by ptr727** [comment]
I've never used plugins, "I don't know why", I don't know why either.  
LSIO images relink some locations, see the [readme](https://github.com/ptr727/NxWitness#volumes).

Did you try to attach to the running container to see what is going on inside it?  
`docker exec --interactive --tty [containername] /bin/bash`

Did you ask Nx support or in the Nx forum?

**Comment by ckuntze** [comment]
Hello,

i know whit the relink - thanks. 
There wasn't enough time for the logs

I have setup a secund Synology with ext4 and docker.
There i install a new Container whit 5.0 LSIO (its run), whit 5.1 can´t start the Container (not enought time to check - sorry)

**Comment by ptr727** [comment]
Insufficient information provided, does not appear to be an issue with this project.
