### ISSUE TITLE
ARM version

### ISSUE THREAD

**Issue by hendrikTpl** [ptr727/NxWitness#131]
### Describe the problem?

```
docker pull ptr727/nxmeta-lsio:latest
latest: Pulling from ptr727/nxmeta-lsio
no matching manifest for linux/arm64/v8 in the manifest list entries
```
no support for ARM version.

the official NxMeta installer download page, it has arm version
https://meta.nxvms.com/download/arm

how to update ptr727/nxmeta-lsio to support ARM devices likewise in the official NxMeta software

**Comment by ptr727** [comment]
To my knowledge ARM is supported on hardware only, if you can point me to confirmation that docker ARM is supported I can take a look.

**Comment by hendrikTpl** [comment]
Thanks for your reply.
the idea is to modify the [Dockerfile](https://github.com/ptr727/NxWitness/blob/main/NxMeta-LSIO/Dockerfile) base using [https://hub.docker.com/r/lsiobase/ubuntu/tags](https://hub.docker.com/r/lsiobase/ubuntu/tags) using linux/arm64 then use _metavms-server-5.1.2.37996-linux_arm64.deb_ from https://meta.nxvms.com/download/arm

```
ARG DOWNLOAD_URL="https://updates.networkoptix.com/metavms/37996/metavms-server_update-5.1.2.37996-linux_x64.zip"
ARG DOWNLOAD_VERSION="5.1.2.37996"
```
I am not sure how to customize it using your repo.
any suggestion would be great

**Comment by ptr727** [comment]
I understand the mechanics, I have not seen docker support for ARM mentioned anywhere by Network Optix as supported ARM devices are limited to specific hardware, have you seen Nx mention ARM support for docker?
