### ISSUE TITLE
Docker images not created for "5.1.3.38363"

### ISSUE THREAD

**Issue by mrjvb** [ptr727/NxWitness#138]
Hi, thank you a lot for the NXWitness Docker images. I noted that for the latest stable release "5.1.3.38363" of 11 March 2024 no Docker images are created. Again thanks for your work.

**Comment by mrjvb** [comment]
Hi, thank you a lot for the NXWitness Docker images. I noted that for the latest stable release "5.1.3.38363" of 11 March 2024 no Docker images are created. Again thanks for your work on these.

**Comment by ptr727** [comment]
5.1.3 has not been [released](https://updates.vmsproxy.com/default/releases.json), `release_date` is `null` and `release_delivery_days` is `null`.

**Comment by mrjvb** [comment]
I saw that the `release_date` was missing, guess that was the reason for the build not to happen. Must be an oversight of NXW, version is released however as can be seen at [https://updates.networkoptix.com/default/#note_5.1.3.38363].
