### ISSUE TITLE
Replace Self-Signed Certificate

### ISSUE THREAD

**Issue by kikaida** [ptr727/NxWitness#149]
### Describe the problem?

Currently using dwspectrum-lsio:5.1.3.38363

Volume is /home/me/dwspectrum/config:/config

When I replace the default.pem file with my own certificate in /home/me/dwspectrum/config/var/ssl and restart the container, the container generates a new self-signed certificate overwriting my custom default.pem. Anyway to make my custom ssl certificate stick?

**Comment by ptr727** [comment]
This is not an issue that seems to be related to the docker build, maybe ask Nx.
