### ISSUE TITLE
/media is not being detected

### ISSUE THREAD

**Issue by cri5py** [ptr727/NxWitness#154]
### Describe the problem?

Hi,

It seems that I'm having an issue where the docker uses the /config/HD Witness Media directory to store recordings.

My understanding is that it should be saving the files in /media.

Under storage Locations, it only displays the /config/HD Witness Media directory as a storage location.

/config/HD Witness Media Info
 Server 

 Type 

 Server
 local
State
 Status 

 Issues (24h) 

 Online
 _
Activity
 Read Rate 

 Write Rate 

 Transactions/s 

 0 Mbit/s
 0 Mbit/s
 0 Tr/s
Space
 Total 

 VMS Media(%) 

 VMS Media 

 21991 GB
 0 %
 0 GB

I am using the lsio:

```
docker run -d \
--name=nxWitness \
--restart=unless-stopped \
--net=host \
-e PUID=1030 -e PGID=101 \
-e TZ=America/New York \
-v /volume2/docker/nxwitness:/config \
-v /volume1/DVR:/media \
ptr727/nxwitness-lsio
```

**Comment by ptr727** [comment]
Did you try any of the [Troubleshooting](https://github.com/ptr727/NxWitness?tab=readme-ov-file#troubleshooting) steps, specifically the Missing Storage section?

As  for where it "should be saving", this is non-deterministic, Nx internally decides what storage it will make available for use, there is no specific mount point or folder it uses, you could mount `/foo` and it may use it. You need to make sure the storage you want to use is listed, and then select it if available, or figure out why it is not listed.

**Comment by cri5py** [comment]
I did not. Thank you for the link. I'm going to look into this. Appreciate the help
