### ISSUE TITLE
Feature Request: Support for Nx Go

### ISSUE THREAD

**Issue by kinnairdclan** [ptr727/NxWitness#171]
### Describe the problem?

Was wondering if you'd be willing to support another couple of containers, specifically Nx Go Server.

The Nx Go Dashboard exists behind user authentication, but the URLs to support Nx Go Server builds are publically accessible:

https://cloud.nxgo.io/download/releases/windows

**Comment by ptr727** [comment]
I'll take a look when I have some time.

**Comment by kinnairdclan** [comment]
PR to support it here.

https://github.com/ptr727/NxWitness/pull/172

Everything should be in place except any pertinent GitHub actions changes for a new container (if that's even necessary).

Please advise if you'd like me to thoroughly test my fork's GitHub actions before we go ahead with this, because it is untested, and was not even enabled. I did not want to create dozens of container repos in Docker Hub just to see if everything worked, but I can.

The Nx Go Dockerfiles did create successfully alongside the others.
