### ISSUE TITLE
`DWSpectrum` container does not continue running

### ISSUE THREAD

**Issue by jmpolom** [ptr727/NxWitness#31]
Using podman as a user to run `docker.io/ptr727/dwspectrum` as a rootless container results in a container that doesn't continue to run, unlike the `docker.io/ptr727/dwspectrum-lsio` image. This is on a Debian Bullseye (Testing) host with podman 3.0.1.

Podman run command:
```
podman run --cgroups=no-conmon   --detach --pull=always   --log-driver=journald   --log-opt tag=dwspectrum   --name=dwspectrum   --env TZ=Americas/Detroit   --hostname=watchdog   --dns-search=subly.me   --publish 7001:7001   --volume /tank/enc/dwspectrum/config:/config   --volume /tank/enc/dwspectrum/media:/media   --volume /tank/enc/dwspectrum/archive:/archive   docker.io/ptr727/dwspectrum:4.2.0.32660
```

The above command was run by a user. I ran the same command as root (rootful container) but didn't notice different behavior. The container still did not continue to run in the background after issuing the command.

I've resorted to using the `dwspectrum-lsio` image which works but I'm curious why the non-LSIO image doesn't continue to run.

**Comment by ptr727** [comment]
Hmm, I noticed that Nx "recently" made changes to their default docker startup, something I've not mimicked yet.
See:
https://github.com/networkoptix/nx_open_integrations/blob/master/docker/Dockerfile
vs.
https://github.com/ptr727/NxWitness/blob/main/NxWitness/Dockerfile

I personally use the LSIO non-root variant, but I'll try to update the non-LSIO versions to match the new Nx startup scheme.

And I assume you mean `ptr727` not `ptr707` ;)

**Comment by jmpolom** [comment]
Does the NxWitness/DW Spectrum assume that systemd is present to run the service? Is the issue with the non-LSIO variant that systemd is not properly supported in the container? I haven't dug into this in enough detail to be intelligent on this matter but this was my suspicion since the LSIO image runs S6 to manage in container processes.

And yes, `ptr727` was what I intended and I've updated the original comment.

**Comment by ptr727** [comment]
I changed the non-LSIO images to use a custom ENTRYPOINT to launch an `entrypoint.sh` script, i.e. no longer using systemd.
But, this will only work for root, i.e. root-tool needs to run as root.

The Nx reference docker script, adds the user to sudoers group to run the root-tool as sudo, I am not convinced that this is the right way to go from a security perspective, vs. separating root vs. non-root.

I have no experience with podman, but if you can't get LSIO to work with rootless podman, maybe you can try the Nx docker scripts?

**Comment by jmpolom** [comment]
The LSIO images work great with podman and I suspect it’s because they’re using s6 for process management. It’s the non-LSIO images that don’t seem to work.

With rootless podman, whether the command runs as root or a user inside the container is sort of immaterial since the container is both unprivileged and running as a user on the host. It’s certainly cleaner to run the entrypoint script directly as root.

I will try and test your changes out during the week. I have a feeling there was something wonky going on between the networkoptix server and systemd inside the container and that is why they decided to directly run the server instead of rely on the init system.

**Comment by ptr727** [comment]
> I have a feeling there was something wonky going on between the networkoptix server and systemd inside the container and that is why they decided to directly run the server instead of rely on the init system.

Running systemd in a container is an anti-pattern, and like they say, not the way to use docker, so in my opinion a welcome change.

The non-LSIO version may run as non-root, but the account only has context inside docker, it does not directly map to a host counterpart.

If LSIO version works I'd suggest you use it, for the user you specify using PUID maps to an actual user on the host, allowing granular file permission logic for the volume mappings.

**Comment by jmpolom** [comment]
> Running systemd in a container is an anti-pattern, and like they say, not the way to use docker, so in my opinion a welcome change.

Absolutely. I’m guessing the ubuntu base images aren’t systemd containers and that’s the issue. It does seem like the LSIO base is the way to go here if you want an in-container process supervisor. I’ll definitely give the non-LSIO variant a try though to see if the issue appeared to be systemd.
