### ISSUE TITLE
Info: Synolog DS916+ ok / RS2818RP+ error

### ISSUE THREAD

**Issue by ckuntze** [ptr727/NxWitness#45]
Hello
only an Info

Installing on Synology DS916+, RS2818RP+, DS1621+.

On DS916+ all ok

On RS2818RP+ and DS1621+ no databas, archive, media
[Synology.txt](https://github.com/ptr727/NxWitness/files/9035122/Synology.txt)
.

**Comment by ptr727** [comment]
Can't really help much, suggest you enable debug logging, and see if the maybe the filesystems are filtered out.
See the [notes](https://github.com/ptr727/NxWitness#notes) section on storage.

**Comment by ckuntze** [comment]
I will make the days I have yet to set up a test environment.

The other trials were in an active Windows environment with 80 licenses with 120 cameras. I tested the Synolgys as FailOver.

**Comment by ckuntze** [comment]
Is that how you need it?
[log_file.log](https://github.com/ptr727/NxWitness/files/9041591/log_file.log)

**Comment by ptr727** [comment]
Please do note I cannot provide support for Nx, I simply create automated docker builds, if you have a problem with my docker builds, I am happy to help, but I can't help with Nx issues, please post in their support forum.

That said...

The log does not contain DEBUG messages, you need to enable debug logging.
Edit /config/etc/mediaserver.conf and set logLevel=DEBUG2, restart

To verify storage, log onto the server web admin page, and verify that storage is available.
After logging into the web admin page, go to Monitoring/Storage, and make sure you see the mapped volumes there.
E.g. https://[IP]:7001/static/index.html#/info

**Comment by ckuntze** [comment]
Here the new file
[log_file (3).log](https://github.com/ptr727/NxWitness/files/9041722/log_file.3.log)
![Screenshot 2022-07-04 212959](https://user-images.githubusercontent.com/96942167/177209145-d4eb918c-200d-446d-a744-0ef9a3ea05f0.jpg)

This is on DS1621+ with all Updates (same Problem on RS2818RP+)

@DS916+ is all OK

**Comment by ptr727** [comment]
Looks like the issue with duplicates or BTRFS not [supported](https://github.com/networkoptix/nx_open_integrations/tree/master/docker#notes-about-storage), see the [notes](https://github.com/ptr727/NxWitness#notes).

```
2022-07-04 19:28:30.344    125 VERBOSE nx::vms::server::fs: /dev/mapper/cachedev_0 /media btrfs - duplicate
2022-07-04 19:28:30.344    125 VERBOSE nx::vms::server::fs: /dev/mapper/cachedev_0 /config btrfs - duplicate
2022-07-04 19:28:30.344    125 VERBOSE nx::vms::server::fs: /dev/mapper/cachedev_0 /archive btrfs - duplicate
2022-07-04 19:28:30.344    125 VERBOSE nx::vms::server::fs: /dev/mapper/cachedev_0 /backup btrfs - duplicate
```

```
2022-07-04 19:28:30.346    125   DEBUG QnStorageSpaceRestHandler(0x7f85043b0b00): Return 0 storages and 1 protocols
```

Try adding `btrfs` as a supported FS, if still no go I'd suggest you contact Nx support.
Look in notes under the `Version 4.1+ added the ability to specify additional storage filesystem types.` heading

**Comment by ckuntze** [comment]
Ok

Thanks,

**Comment by ptr727** [comment]
Added some details here: https://github.com/ptr727/NxWitness#missing-storage
