### ISSUE TITLE
Expose Plugin Folder as a Volume

### ISSUE THREAD

**Issue by kizza42** [ptr727/NxWitness#64]
I have been using this container for some home recording/testing and though I'd have a play with the Open Vino plugin but unfortunately the system/plugin folders aren't exposed. Would it be possible to add them as a volume please?

**Comment by ptr727** [comment]
You can use normal docker functionality and map any file or folder in your deployment, it does not have to be a known pre-defined volume in the base container.
E.g. `- /mnt/nxwitness/plugins:/opt/networkoptix/mediaserver/bin/plugins`

**Comment by kizza42** [comment]
🤦‍♀️ Thankyou
