### ISSUE TITLE
Docker access

### ISSUE THREAD

**Issue by yotux** [ptr727/NxWitness#68]
I followed the docker compose script, container is running but not accessible via local address ending in 10.10.x.x:7001

**Comment by ptr727** [comment]
This does not appear to be an issue with this project, possibly with your use or environment.

I'll try to help, but you are not providing details that could help you in resolving the problem.
How about your compose yaml, log output, etc., anything that could help me help you?

**Comment by ptr727** [comment]
Closing due to no response.
