### ISSUE TITLE
Storage errors when using SMB

### ISSUE THREAD

**Issue by btstromberg** [ptr727/NxWitness#99]
### Describe the problem?

This is not really an issue with the container, but I have spent a good amount of time before I could figure it out and I thought I'd leave it here in case someone else run into the same issue. And I'm not sure how to make proper pull requests/working with Github overall.

I use a separate NAS (Synology) for media storage, and the Docker host is a Debian VM. So what I did was to mount the file share in the docker host via SMB. And then bind mount that into the container at /media. This worked, kind of. But there was a generic storage error message constantly popping up. And I could tell that some of the analytics data (motion tracking, metadata etc) was nowhere to be found, even if the video files got saved to the NAS.

So in order for the analytics db to work, you have to mount the NAS folder using NFS in the container using a volume. Here is my compose config:

`services:
  nxwitness:
    <<: *common-keys-core
    image: docker.io/ptr727/nxwitness-lsio:stable
    container_name: nxwitness
    restart: unless-stopped
    network_mode: host
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - /opt/docker/data/nxwitness/config:/config
      - nxwitness-vol:/media
volumes:
  nxwitness-vol:
    driver_opts:
      type: "nfs"
      o: "addr=10.180.10.22,nfsvers=4"
      device: ":/volume1/nxwitness-meta"`

Now you can configure /media as a location for analytics data. It will warn about it being a local path but that warning can be ignored.

**Comment by ptr727** [comment]
As this is not an issue with the docker builds per se, I'd suggest you post this in the Nx developer forum.
